import Link from "next/link";

export default function Home() {
  return <main>
    <section className="clouds min-h-[760px] px-5 pt-5">
      <nav className="mx-auto flex max-w-[1260px] items-center justify-between rounded-2xl bg-white/95 px-5 py-3 shadow-sm">
        <Link href="/" className="naano-logo"><span className="logo-mark"><i /></span>naano</Link>
        <div className="desktop-nav flex items-center gap-7 text-[13px] font-medium">
          <a href="#companies">For companies</a><a href="#creators">For creators</a><a href="#agencies">For agencies</a><a href="#how">How it works</a><Link href="/pricing">Pricing</Link>
        </div>
        <div className="flex items-center gap-2"><Link className="btn-white text-sm" href="/login">Sign in</Link><Link className="btn-black !px-5 !py-[11px] text-sm" href="/register">Sign up</Link></div>
      </nav>
      <div className="mx-auto flex max-w-[980px] flex-col items-center pt-28 text-center">
        <div className="fade-up mb-7 rounded-full border border-white bg-white/70 px-4 py-2 text-xs font-semibold shadow-sm backdrop-blur"><span className="mr-2">𝕏</span> Where B2B brands work with creators <span className="ml-2 rounded bg-[#0A66C2] px-1 py-0.5 text-white">in</span></div>
        <h1 className="fade-up-2 max-w-[890px] text-[50px] font-semibold leading-[1.02] tracking-[-.055em] sm:text-[76px]">The B2B LinkedIn<br/>Creator Marketplace.</h1>
        <p className="fade-up-3 mt-7 max-w-[700px] text-lg leading-7 text-[#57575c]">Find the creators your buyers already trust, launch campaigns in days, and track the clicks, leads and pipeline generated by every post.</p>
        <div className="mt-9 flex flex-wrap items-center justify-center gap-6"><Link className="btn-black !px-7 !py-4" href="/register">Launch a campaign →</Link><a className="font-semibold" href="#how">See how Naano works →</a></div>
        <p className="mt-10 text-xs font-medium tracking-wide text-[#7a7a80]">Trusted by modern B2B teams</p>
        <div className="mt-5 flex flex-wrap items-center justify-center gap-x-10 gap-y-4 text-[15px] font-semibold text-[#8a8a90]/80"><span>ringover</span><span>attio</span><span>La Growth Machine</span><span>lemlist</span><span>ChatSEO</span><span>Abyssale</span><span>BlogSEO</span></div>
      </div>
    </section>
    <section id="creators" className="mx-auto max-w-[1180px] px-6 py-24">
      <p className="eyebrow">For creators</p>
      <h2 className="mt-4 max-w-[640px] text-4xl font-semibold tracking-[-.04em] sm:text-5xl">Get paid for the LinkedIn posts you already know how to write.</h2>
      <p className="mt-5 max-w-[620px] leading-7 text-[#666]">Set a fixed price per post, pick the brands you want to work with, and get paid after the post is approved. No media kit ping pong.</p>
      <div className="mt-12 grid gap-5 md:grid-cols-3">
        {[["Set your price","From €20 per LinkedIn post. You keep control."],["Work with B2B brands","SaaS, sales tools and operators who actually buy."],["Payouts after approval","Stripe payout once the brand signs off."]].map(x=>(
          <div className="card p-7" key={x[0]}><h3 className="text-xl font-semibold">{x[0]}</h3><p className="mt-3 leading-6 text-[#666]">{x[1]}</p></div>
        ))}
      </div>
      <Link className="btn-black mt-10 inline-flex" href="/register">Join as a creator →</Link>
    </section>
    <section id="agencies" className="bg-[#f7f7f6] px-6 py-24">
      <div className="mx-auto max-w-[1180px] grid gap-10 lg:grid-cols-2 lg:items-center">
        <div>
          <p className="eyebrow">For agencies</p>
          <h2 className="mt-4 text-4xl font-semibold tracking-[-.04em]">Run creator campaigns for more than one client, without a spreadsheet.</h2>
          <p className="mt-4 leading-7 text-[#666]">Brief, book, approve and report from one workspace. White-label the tracking if you need to.</p>
          <Link className="btn-black mt-8 inline-flex" href="/register">Talk to naano →</Link>
        </div>
        <div className="card p-8">
          <p className="text-sm font-semibold">Agency workspace</p>
          <ul className="mt-6 grid gap-4 text-sm text-[#555]">
            <li>✓ Multi-brand campaigns</li>
            <li>✓ Shared creator shortlists</li>
            <li>✓ Client-ready performance reports</li>
            <li>✓ Managed support at €700/month</li>
          </ul>
        </div>
      </div>
    </section>
    <section className="border-y border-[#ededed] bg-white px-6 py-10">
      <p className="mb-7 text-center text-xs text-[#8a8a8f]">TRUSTED BY FAST-GROWING B2B TEAMS</p>
      <div className="mx-auto flex max-w-[1100px] flex-wrap items-center justify-center gap-x-12 gap-y-6 text-xl font-bold tracking-tight text-[#59595d]"><span>ringover</span><span>attio</span><span>La Growth Machine</span><span>lemlist</span><span>ChatSEO</span><span>Abyssale</span><span>BlogSEO</span></div>
    </section>
    <section id="how" className="mx-auto max-w-[1180px] px-6 py-28">
      <p className="eyebrow text-center">Built for B2B outcomes</p>
      <h2 className="mx-auto mt-4 max-w-[700px] text-center text-4xl font-semibold tracking-[-.04em] sm:text-5xl">From creator discovery to measurable pipeline.</h2>
      <div className="mt-16 grid gap-5 md:grid-cols-3">
        {[["01","Find the right voice","Search vetted creators by audience, expertise, reach and brand fit."],["02","Launch in days","Share one brief, collaborate on drafts and book fixed-price posts."],["03","Prove every result","See clicks, leads and attributed pipeline for every creator and post."]].map(x=><div className="card p-8" key={x[0]}><span className="text-sm text-[#315cff]">{x[0]}</span><h3 className="mt-14 text-2xl font-semibold">{x[1]}</h3><p className="mt-3 leading-6 text-[#6e6e73]">{x[2]}</p></div>)}
      </div>
    </section>
    <section id="companies" className="bg-[#f7f7f6] px-6 py-24">
      <div className="mx-auto max-w-[1100px] grid gap-10 lg:grid-cols-2 lg:items-center">
        <div>
          <p className="eyebrow">Case study</p>
          <h2 className="mt-4 text-4xl font-semibold tracking-[-.04em]">How BlogSEO turned creator content into product signups</h2>
          <p className="mt-4 leading-7 text-[#666]">BlogSEO briefed SEO and SaaS creators on LinkedIn, then traced every trial back to the post that drove it.</p>
          <blockquote className="mt-6 text-lg font-medium leading-8">“Naano became one of our fastest acquisition channels. We know exactly what every creator brings.”</blockquote>
          <p className="mt-3 text-sm text-[#888]">Vincent Josse · CEO, BlogSEO</p>
        </div>
        <div className="grid grid-cols-3 gap-3">
          {[["9","creators activated"],["2,940","qualified clicks"],["512","trials started"]].map(x=>(
            <div className="card p-5" key={x[1]}><b className="block text-3xl tracking-tight">{x[0]}</b><small className="mt-2 block text-[#777]">{x[1]}</small></div>
          ))}
        </div>
      </div>
    </section>
    <section className="px-6 py-20">
      <div className="mx-auto grid max-w-[1100px] gap-6 sm:grid-cols-4 text-center">
        {[["5M+","Impressions"],["30K+","Leads"],["2,000+","Creators"],["5K+","Posts published"]].map(x=>(
          <div key={x[1]}><b className="block text-4xl tracking-tight">{x[0]}</b><p className="mt-2 text-sm text-[#777]">{x[1]}</p></div>
        ))}
      </div>
    </section>
    <section id="resources" className="mx-auto max-w-[920px] px-6 py-16">
      <h2 className="text-center text-4xl font-semibold tracking-tight">Frequently asked questions</h2>
      <div className="mt-10 grid gap-3">
        {[
          ["What is Naano?","Naano is a B2B LinkedIn creator marketplace. Companies book vetted creators for sponsored posts at a fixed price per post."],
          ["How does per-post pricing work?","Each creator sets a flat fee. Campaigns start from €20. No CPC, no impression billing."],
          ["Do you handle payouts?","Yes. Creators get paid automatically after the post is approved."],
          ["What's the difference between Free and Done for you?","Self-Serve is €0/month. Managed Campaigns is €700/month and Naano runs sourcing, briefs and reporting for you."],
        ].map(x=>(
          <details key={x[0]} className="card p-5">
            <summary className="cursor-pointer font-semibold">{x[0]}</summary>
            <p className="mt-3 leading-6 text-[#666]">{x[1]}</p>
          </details>
        ))}
      </div>
    </section>
    <section className="bg-[#111] px-6 py-24 text-center text-white"><h2 className="text-4xl font-semibold tracking-tight">Your next buyer already follows them.</h2><p className="mx-auto mt-4 max-w-xl text-[#aaa]">Start with a creator your market trusts. Posts start at €20.</p><Link className="mt-8 inline-flex rounded-full bg-white px-7 py-4 font-semibold text-black" href="/register">Explore creators →</Link></section>
    <footer className="border-t border-[#eee] px-6 py-8 text-center text-sm text-[#777]">naano · B2B LinkedIn creator marketplace · Self-Serve €0/mo · Managed €700/mo</footer>
  </main>;
}
