import Link from "next/link";

const plans=[
 {name:"Self-Serve",price:"€0",desc:"For teams ready to run creator campaigns in-house.",cta:"Start for free",features:["Browse 15,000+ vetted creators","Book fixed-price LinkedIn posts","Campaign collaboration workspace","Click, lead & pipeline tracking","No platform subscription"]},
 {name:"Managed",price:"€700",desc:"For teams that want a dedicated creator campaign partner.",cta:"Talk to our team",features:["Everything in Self-Serve","Dedicated campaign strategist","Creator sourcing & negotiation","Brief writing and quality review","Monthly performance report"]}
];
export default function Pricing(){
 return <main><nav className="mx-auto flex max-w-[1200px] items-center justify-between px-6 py-5"><Link href="/" className="naano-logo"><span className="logo-mark"><i/></span>naano</Link><div className="flex gap-3"><Link href="/login" className="btn-white">Sign in</Link><Link href="/register" className="btn-black">Get started</Link></div></nav><section className="px-6 pb-24 pt-24 text-center"><p className="eyebrow">Simple pricing</p><h1 className="mx-auto mt-4 max-w-3xl text-5xl font-semibold tracking-[-.045em] sm:text-6xl">Start free. Add expertise when you need it.</h1><p className="mx-auto mt-6 max-w-xl text-lg leading-7 text-[#6d6d72]">Creators set their own fixed price. You only pay for the posts you book. Posts start at €20.</p><div className="mx-auto mt-16 grid max-w-[920px] gap-5 text-left md:grid-cols-2">{plans.map((p,i)=><div className={`card relative p-8 ${i?"border-[#315cff]":""}`} key={p.name}>{i===1&&<span className="absolute right-6 top-6 rounded-full bg-[#315cff] px-3 py-1 text-xs font-semibold text-white">Most support</span>}<p className="eyebrow">{p.name}</p><div className="mt-5"><b className="text-5xl">{p.price}</b><span className="text-[#777]"> / month</span></div><p className="mt-5 min-h-12 leading-6 text-[#666]">{p.desc}</p><Link href="/register" className={`mt-7 w-full ${i?"btn-black":"btn-white"} !rounded-xl text-center`}>{p.cta} →</Link><ul className="mt-8 grid gap-4 border-t border-[#eee] pt-7 text-sm">{p.features.map(f=><li key={f}>✓ &nbsp;{f}</li>)}</ul></div>)}</div></section><footer className="border-t border-[#eee] px-6 py-8 text-center text-sm text-[#777]">naano · B2B creator campaigns that drive pipeline</footer></main>
}
